import Header from "../components/Header";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import AuthProvider from "./provider/authProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}